"""
Django settings for buffer_clone project.
Generated by 'django-admin startproject' using Django 5.x
"""

from pathlib import Path
import dj_database_url
import os

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "replace_with_a_random_secret_key_for_dev"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "social_auth",
    "posts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "buffer_clone.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "buffer_clone.wsgi.application"

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Whitenoise settings
MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login settings
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# === Social API Credentials ===

# Facebook Scopes
FB_SCOPES = [
    "pages_show_list",
    "pages_manage_posts",
    "pages_read_engagement",
    "public_profile"
]

# Instagram Scopes
IG_SCOPES = [
    "instagram_basic",
    "instagram_content_publish",
    "pages_show_list"  # Needed to fetch Instagram business account
]


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8000/accounts/login/",
    "http://127.0.0.1:8000"
]

# ---------------- SOCIAL AUTH SETTINGS ----------------
# Meta App credentials (shared for Facebook & Instagram)
META_APP_ID = "757636776676066"
META_APP_SECRET = "1feb2af766be229e4c8efcec591a7871"

# Redirect URIs
FACEBOOK_REDIRECT_URI = "http://localhost:8000/callback/facebook/"
INSTAGRAM_REDIRECT_URI = "http://localhost:8000/callback/instagram/"

# LinkedIn
LINKEDIN_CLIENT_ID = "86rx83jdom8v6h"
LINKEDIN_CLIENT_SECRET = "WPL_AP1.zjdOyeBm43xUCyyq.Uki6Hg=="
LINKEDIN_REDIRECT_URI = "http://localhost:8000/callback/linkedin/"


# Your manually obtained LinkedIn personId
LINKEDIN_PERSON_URN = "urn:li:person:kLCpM-rGBP"
LINKEDIN_ACCESS_TOKEN = 'AQUs0QXToSG1m2lR8UCNlXfM6HhJ1N9k9Vx-4QPDHnWh9pVz0xIMqlOFqTNfR_PtWvVfdaa_2uRd8zWUUjYWUZ8nngRyovZ-W3rz8N2GBm69y76xvxMNgfJzWXSU81jtCucqcY2Am03VwVdPrF_Orq2H96PltQFiHvApOU03tgR6SHp9FZn76x89xA9vbtc0kYX0qol0UEYVwJBfFrvxSUSs2WhUaGpkqCWeuhyb0T3rMW2oW3rhnNRXWPhQvdD1954W8Bkfow8nkehzOFthQ2pdm2z6XEvP5iaZcOJUKRDZWoVjsc1YwKysd_ZhOmNgdubRpEb9w8n6dwZQMWkiEcAHmd3JYw'
